package lk.iit.nextora.infrastructure.notification.push.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request DTO for registering an FCM token.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FcmTokenRequest {

    /**
     * FCM token generated by Firebase Web SDK.
     */
    @NotBlank(message = "Token is required")
    @Size(max = 500, message = "Token exceeds maximum length")
    private String token;

    /**
     * Optional device type for analytics.
     */
    @Size(max = 50, message = "Device type exceeds maximum length")
    private String deviceType;
}
